apiVersion: apps/v1
kind: Deployment
metadata:
  name: skill-boost-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skill-boost-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: skill-boost-app
    spec:
      containers:
        - name: skill-boost-app
          image: skill-boost:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          envFrom:
            - secretRef:
                name: db-secret
            - secretRef:
                name: app-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: skill-boost-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: skill-boost-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skill-boost-app-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skill-boost-app
                port:
                  number: 80
